### PR TITLE
Fix download link of hatohol.repo

### PR DESCRIPTION
**Pull request by Mnakagawa**

### CODE REVIEW

**Comment by bynnchapu** [comment]
BTW, did you try to install Hatohol RPM using following repofile on each environment ?

- https://github.com/project-hatohol/project-hatohol.github.io/raw/master/repo/hatohol-el6.repo
- https://github.com/project-hatohol/project-hatohol.github.io/raw/master/repo/hatohol-el7.repo

**Comment by Mnakagawa** [comment]
> did you try to install Hatohol RPM using following repofile on each environment ?

Of course.

**Comment by bynnchapu** [comment]
Please deploy it onto website server.

**Comment by Mnakagawa** [comment]
> Please deploy it onto website server.

It's already finished.
Please check it.

**Pull request merged**
