### PR TITLE
Use bundler

### PR DESCRIPTION
**Pull request by cosmo0920**
Installing gems globally is not good.
Please install them via bundler instead.

### CODE REVIEW

**Comment by cosmo0920** [comment]
@Mnakagawa Any concerns?

**Comment by Mnakagawa** [comment]
This PR looks so good.
I want to check it in my environment.
Can you wait a little?
I may be going to check it around noonof today.

**Comment by cosmo0920** [comment]
Thanks.
Please let me know if there is any problem.

**Comment by Mnakagawa** [comment]
OK. I checked it.

**Comment by cosmo0920** [comment]
:+1:

**Pull request merged**
